project:
  type: website

website:
  title: "Jiru"
  site-url: https://JiruHan.id.au
  description: "Jiru Han's personal website"
  favicon: icon.png
  navbar:
    pinned: true
    left:
      - posts/index.qmd
      - projects/index.qmd
      - talks/index.qmd
      - publications/index.qmd
    right:
      - icon: github
        href: https://github.com/JiruHan
      - icon: rss
        href: posts/index.xml
  page-footer:
    left:
      - text: "© 2017-2026, Jiru Han"
    right:
      - text: "License"
        href: license.qmd
  open-graph:
    locale: en_AU
    site-name: Jiru
  cookie-consent:
    palette: dark
header-includes: |
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500&family=Rubik:wght@300;400;500;700&display=swap" rel="stylesheet">
  <script>
    window.addEventListener("load", () => {
      if (window.quartoToggleHeadroom) {
        window.quartoToggleHeadroom();
        window.quartoToggleHeadroom = () => {};
      }
    });
  </script>
format:
  html:
    theme:
      light: [flatly, css/custom.scss]
      dark: [darkly, css/custom.scss, css/dark.scss]
    mainfont: "Rubik"
    monofont: "Fira Code"
